### ISSUE TITLE
An error is returned if there is no option given with no value

### ISSUE THREAD

**Issue by derekpcollins** [derekpcollins/jquery-custom-select-menu#18]
I need to dig into this more, but I found that if a default option (e.g. Choose one...) with no value doesn't exist, the following JavaScript error is given: "Uncaught TypeError: Cannot call method 'val' of undefined"

**Comment by micbra** [comment]
I had this issue, too. As a workaround I moved the following two lines of code from line 114 to line 75:

``` javascript
// Create a hidden input field so we can keep track of which option they choose
newHiddenInput = $( '<input type="hidden" name="' + selectName + '" value="" />' );
```

Seems that `newHiddenInput` was used before it was defined...
